.TH "QTORRENT" "1" "March 2017" "qTorrent" ""

.SH NAME
qTorrent \- a BitTorrent client in C++ with Qt5

.SH SYNOPSIS

\fBqTorrent\fR
.PP
.SH "DESCRIPTION"

\fBqTorrent\fR is a simple BitTorrent client, written from scratch in C++ with Qt5.
qTorrent aims to be a good, lightweight alternative to all the other BitTorrent clients.
.br
It provides the minimal features required for a standard BitTorrent client.
.PP
.SH "AUTHOR"

Petko Georgiev <petko.vas.georgiev@gmail.com>
